version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
