version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment: # Add environment variable for CORS origin
      SOCKETIO_CORS_ORIGIN: "http://client:3000"
    command: ["sh", "-c", "sleep 5 && nodemon index.js"]
