version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://server:4000 # Set the server URL
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      SOCKETIO_CORS_ORIGIN: "http://client:3000"
    command: ["sh", "-c", "sleep 10 && nodemon index.js"]
     
