version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: host  # Connect the container to the host network
    # Remove the "networks" section for the client service

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      SOCKETIO_CORS_ORIGIN: "http://client:3000"
    command: ["sh", "-c", "sleep 10 && nodemon index.js"]
    network_mode: host  # Connect the container to the host network
    # Remove the "networks" section for the server service
