 
version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      app-network:
        ipv4_address: 172.21.0.2  # Replace with the desired IP address

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    environment: # Add environment variable for CORS origin
      SOCKETIO_CORS_ORIGIN: "http://172.21.0.2:80"
    command: ["sh", "-c", "sleep 10 && nodemon index.js"]
    networks:
      app-network:
        ipv4_address: 172.21.0.3  # Replace with the desired IP address

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16  # Replace with your desired subnet
